<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="RACD-002157" name="Default test" tests="11" failures="1" timestamp="23 May 2019 09:24:36 GMT" time="26.224" errors="0">
  <testcase name="TrackTransferModule" time="0.01" classname="com.qa.extentreport.TestClass.TestOfExtentReport"/>
  <testcase name="EnterWrongMTCNNumber" time="0.001" classname="com.qa.extentreport.TestClass.TestOfExtentReport"/>
  <testcase name="ErrorMessageInString" time="0.002" classname="com.qa.extentreport.TestClass.TestOfExtentReport"/>
  <testcase name="ErrorMessageInNumber" time="0.002" classname="com.qa.extentreport.TestClass.TestOfExtentReport"/>
  <testcase name="EnterCorrectMTCNnumber" time="0.001" classname="com.qa.extentreport.TestClass.TestOfExtentReport"/>
  <testcase name="StatusOfValidMTCNnumber" time="3.001" classname="com.qa.extentreport.TestClass.TestOfExtentReport"/>
  <testcase name="TrackNewTransfer" time="0.0" classname="com.qa.extentreport.TestClass.TestOfExtentReport"/>
  <testcase name="DontHaveMTCNNumber" time="0.006" classname="com.qa.extentreport.TestClass.TestOfExtentReport"/>
  <testcase name="SearchMTCNWithoutMTCNNumber" time="0.002" classname="com.qa.extentreport.TestClass.TestOfExtentReport">
    <skipped/>
  </testcase> <!-- SearchMTCNWithoutMTCNNumber -->
  <testcase name="FailingThisMethod" time="0.003" classname="com.qa.extentreport.TestClass.TestOfExtentReport">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:286)
	at org.testng.Assert.assertEquals(Assert.java:296)
	at com.qa.extentreport.TestClass.TestOfExtentReport.FailingThisMethod(TestOfExtentReport.java:114)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- FailingThisMethod -->
  <testcase name="SenderPhoneNumberModule" time="0.001" classname="com.qa.extentreport.TestClass.TestOfExtentReport"/>
</testsuite> <!-- Default test -->
